version: 2
registries:
  maven-google:
    type: maven-repository
    url: maven.google.com
    username: ""
    password: ""
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      
