version: 2
registries:
  google:
    type: maven-repository
    url: dl.google.com/dl/android/maven2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
#    ignore:
#      - dependency-name: com.github.ctiao
#        dependency-version: "0.9.24"
