version: 2
registries:
  maven-google:
    type: maven-repository
    url: dl.google.com/dl/android/maven2/
    username: ""
    password: ""
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    registries:
      - maven-google
    schedule:
      interval: "daily"
      
